# Change these first
owner: kdcokenny # Your GitHub organization or username, where this repository lives
repo: idea-ape-status # The name of this repository

sites:
  - name: IdeaApe
    url: https://ideaape.com
  - name: IdeaApe Dashboard
    url: https://ideaape.com/dashboard
  - name: IdeaApe Auth
    url: https://ideaape.com/auth/continue
  - name: IdeaApe Market Research
    url: https://ideaape.com/market-research
  - name: IdeaApe Business
    url: https://ideaape.com/business
  - name: IdeaApe API
    url: https://ideaape.com/api

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ideaape.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
